$(document).ready(function(){
$(".clickable").click(function(){
  $("#js-on").toggle();
  $("#js-off").toggle();
});
  $(".clickable_01").click(function(){
  $("#operators-on").toggle();
  $("#operators-off").toggle();
});
  $(".clickable_02").click(function(){
  $("#variables-on").toggle();
  $("#variables-off").toggle();
});
});
